version: '3.8'  # Specify the version of the Docker Compose file format

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: sudipm
      POSTGRES_PASSWORD: sudipm
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pg_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-sudipm}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

  config-server-ms:
    image: sudipmanjarekar/config-server-ms:latest
    container_name: config-server-ms
    ports:
      - "8080:8080"
    depends_on:
      - servicereg
    networks:
      - microservice-network
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  servicereg:
    image: sudipmanjarekar/servicereg:latest
    container_name: servicereg
    ports:
      - "8761:8761"
    depends_on:
      - rabbitmq
      - zipkin
      - postgres
      - pgadmin
    networks:
      - microservice-network
      - postgres

  companyms:
    image: sudipmanjarekar/companyms:latest
    container_name: company
    ports:
      - "8081:8081"
    depends_on:
      - servicereg
      - config-server-ms
    networks:
      - microservice-network
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  jobms:
    image: sudipmanjarekar/jobms:latest
    container_name: job
    ports:
      - "8082:8082"
    depends_on:
      - servicereg
      - config-server-ms
    networks:
      - microservice-network
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://servicereg:8761/eureka

  reviewms:
    image: sudipmanjarekar/reviewms:latest
    container_name: review
    ports:
      - "8083:8083"
    depends_on:
      - servicereg
      - config-server-ms
    networks:
      - microservice-network
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - postgres

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # RabbitMQ default port
      - "15672:15672"   # RabbitMQ management console port
    networks:
      - postgres

  gateway-ms:
    image: sudipmanjarekar/gateway-ms:latest
    container_name: gateway-ms
    ports:
      - "8084:8084"
    depends_on:
      - servicereg
    networks:
      - microservice-network
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker

networks:
  microservice-network:
    driver: bridge
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:  # Volume for pgAdmin
